# Generated by Django 4.1.1 on 2024-02-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='db_DairyContent',
            fields=[
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=64)),
                ('Content', models.CharField(max_length=426)),
            ],
            options={
                'db_table': 'DairyContent',
            },
        ),
        migrations.CreateModel(
            name='db_DairyList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('date', models.DateTimeField()),
                ('title', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'DairyList',
            },
        ),
    ]
