# Generated by Django 4.1.1 on 2024-02-22 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dairy', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_dairycontent',
            name='date',
        ),
        migrations.RemoveField(
            model_name='db_dairycontent',
            name='pickdate',
        ),
        migrations.RemoveField(
            model_name='db_dairycontent',
            name='title',
        ),
        migrations.RemoveField(
            model_name='db_dairycontent',
            name='user_id',
        ),
        migrations.AddField(
            model_name='db_dairycontent',
            name='DairyList',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_dairy.db_dairylist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='db_dairycontent',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
