# Generated by Django 4.1.1 on 2024-02-22 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dairy', '0004_remove_db_dairycontent_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='db_DairyContent',
        ),
        migrations.DeleteModel(
            name='db_DairyList',
        ),
    ]
