# Generated by Django 4.1.1 on 2024-02-22 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_dairy', '0005_delete_db_dairycontent_delete_db_dairylist'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_DairyList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=64)),
                ('date', models.DateTimeField()),
                ('pickdate', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'DairyList',
            },
        ),
        migrations.CreateModel(
            name='db_DairyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=9611)),
                ('DairyDetail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dairy.db_dairylist')),
            ],
            options={
                'db_table': 'DairyContent',
            },
        ),
    ]
