# Generated by Django 4.1.1 on 2024-02-22 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dairy', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='班级名称', max_length=12)),
                ('master', models.CharField(help_text='班主任', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='学生姓名', max_length=12)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_dairy.studentclass')),
            ],
        ),
    ]
