# Generated by Django 4.1.1 on 2024-02-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dairy', '0007_studentclass_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='school_class',
        ),
        migrations.DeleteModel(
            name='db_DairyContent',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='StudentClass',
        ),
    ]
