# Generated by Django 4.1.1 on 2024-02-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_dairy', '0011_db_dairycontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='db_DairyContent',
        ),
    ]
