# Generated by Django 4.1.1 on 2024-02-22 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dairy', '0012_delete_db_dairycontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_DairyContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Content', models.CharField(max_length=9611)),
                ('DairyDetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_dairy.db_dairylist')),
            ],
            options={
                'db_table': 'DairyContent',
            },
        ),
    ]
