# Generated by Django 4.1.1 on 2024-02-22 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_dairy', '0014_delete_db_dairycontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_DairyContent',
            fields=[
                ('DairyDetail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app_dairy.db_dairylist')),
                ('Content', models.CharField(max_length=9611)),
            ],
            options={
                'db_table': 'DairyContent',
            },
        ),
    ]
